# Radon Copyright 2021, University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path
from decouple import Csv, config

from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



###################
## Core Settings ##
###################

SECRET_KEY = config("SECRET_KEY", default="django-insecure$project.settings")
DEBUG = config("DEBUG", default=True, cast=bool)
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="127.0.0.1,localhost", cast=Csv())
INSTALLED_APPS = [
    "project.apps.RadonAppConfig",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django_gravatar",
    "rest_framework",
    "django_bootstrap5",
    'django_bootstrap_icons',
    
    "activity",
    "administration",
    "archive",
    "groups",
    "msi",
    "users",
    "settings",
    "rest_cdmi",
    "rest_admin",
]

ROOT_URLCONF = 'project.urls'
INTERNAL_IPS = ["127.0.0.1"]
WSGI_APPLICATION = 'project.wsgi.application'



#########################
## Middleware Settings ##
#########################

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "project.custom.CassandraMiddleware",
]

LOGIN_REDIRECT_URL = "/"
LOGIN_URL = "/users/login"


#######################
## Template Settings ##
#######################

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



#######################
## Database Settings ##
#######################

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


###########################################
## Authentication/Authorization Settings ##
###########################################

AUTH_LDAP_SERVER_URI = None
AUTH_LDAP_USER_DN_TEMPLATE = None

#AUTH_PASSWORD_VALIDATORS = [
#    {
#        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#    },
#    {
#        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#    },
#    {
#        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#    },
#    {
#        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#    },
#]


########################
## I18N/L10N Settings ##
########################

LANGUAGE_CODE = config("LANGUAGE_CODE", default="en-us")
TIME_ZONE = config("TIME_ZONE", default="UTC")
USE_I18N = True
USE_L10N = True
USE_TZ = True
#LOCALE_PATHS = [BASE_DIR / "locale"]


###########################
## Static Files Settings ##
###########################

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")


###################
## REST Settings ##
###################

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        #        'rest_framework.authentication.SessionAuthentication',
        "rest_framework.authentication.BasicAuthentication",
        "project.custom.CassandraAuthentication"
    ],
#         'DEFAULT_PERMISSION_CLASSES': [
#             'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
#     ]
}


##################
## App Settings ##
##################

DEFAULT_APP_CONFIG = "project.RadonAppConfig"
COMPRESS_UPLOADS = False
CDMI_SERVER = {
    "endpoint": "http://127.0.0.1/api/cdmi",
    "username": "",
    "password": "",
}
ADMIN_SERVER = {
    "endpoint": "http://127.0.0.1/api/admin",
}
