name: Release and Docker
on:
  push:
    branches: [main, develop]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write # Obligatoire pour pousser l'image Docker
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.MY_RELEASE_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/github

      - name: Run Semantic Release
        id: semantic # On lui donne un ID pour récupérer sa sortie (la version)
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_TOKEN }}
        run: npx semantic-release

      # --- Étape Docker (Uniquement si une nouvelle version est créée) ---
      
      - name: Login to GitHub Container Registry
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Ici, le token auto suffit pour GHCR

      - name: Build and Push Docker Image
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.semantic.outputs.new_release_version }}